### ISSUE TITLE
Managed Balancer Pools

### ISSUE THREAD

**Issue by MickdeGraaf** [Alexintosh/PIE-landing#100]
#### Description
Currently the Balancer pools used in Pie are finalised, this means the weights and the underlying tokens cannot be changed. The weights and underlying tokens need to be configurable by the DAO while a pool is running. Additionally all balancer pools currently have the same symbol and name BPT, for integration in wallets and viewing on Etherscan all portfolio tokens need a configurable name.

#### Contracts:
- [ ] Wrapper token for managed pool 
- [x] Pool manager contract base
- [ ] Implement standard balancer pool interface in manager contract
- [ ] Allow manager address to bind and unbind tokens
- [ ] Allow manager address to rebind tokens(change weight)
- [ ] Allow manager to set token name and symbol
- [ ] Allow manager to pause trading and adding liquidity
- [ ] Allow manager to set entry, exit, aum and trading fees
- [ ] Allow manager to attach conditions to methods like a max gas price (we might wanna use the aragon acl for this.

**Comment by Alexintosh** [comment]
What is the status of this?
