### ISSUE TITLE
Ready to launch landing page

### ISSUE THREAD

**Issue by Alexintosh** [Alexintosh/PIE-landing#18]
As a PM, I want the landing page be ready to be distributed to the public.

Frontend:
- [ ] Pull Events from Uniswap market to identify when A user bought awp++:
- [ ] #17 Position Recap with Chart
- [ ] #20 Dynamic Newsletter number
- [ ] #16 CTA Retweet
- [x] #12 Web3 Integration
- [x] #13 Detail Trade (Uniswap)
- [x] #14 Uniswap Integration
- [x] #25 Context React web3 data
- [x] #21 Google Analytics
- [x] #19 Mixpanel

Backend:
- [x] #22 Price feed Uniswap
- [ ] #23 Check Balance + Send kETH + kDAI *
```
REF
address: string; unique;
value_input: float;
value_output: float;
ticker: string;
expected_slippage: float;
actual_slippage;
```

Marketing:
- [ ] #24 Seo Check
- [ ] Twitter thread
- [ ] Medium article
- [ ] Pre hype email
