### ISSUE TITLE
Migrate from Set to balancer

### ISSUE THREAD

**Issue by MickdeGraaf** [Alexintosh/PIE-landing#96]
#### Description

As discussed balancer will be a better fit to create portfolio tokens. This epic describes the process of moving from SET to balancer.

#### Frontend:
- [x] Change AWP token address
- [x] Change AWP Uniswap pool address
- [x] Hookup liquidity redeem to balancer pool
- [ ] Hookup liquidity adding to balancer pool

#### Tooling:
- [x] Create buidler task to deploy Balancer factory 
- [x] Create buidler task to deploy Balancer pool from the factory
- [x] Create buidler task to add tokens Balancer pool
- [x] Create buidler task to finalise Balancer pool
- [x] Create buidler task to add liquidity to pool

https://github.com/MickdeGraaf/balancer-buidler-tasks

#### Other
- [x] Create Uniswap market for the new AWP token
- [x] Create Dex basket (ZRX/SNX/BNT/KNC/LRC)
- [x] Create DeFi basket pool token
- [x] Create AWP ++ pool token

**Comment by MickdeGraaf** [comment]
Deployed contracts on kovan:

Balancer factory: 0x25D5f7796FDc83D5bacF8aC3F4bB4bcd6F7e6AD7
Dex basket pool: 0x757b18BB7e183A2a591a144ff9C01f2A893d4A51
DeFi basket pool: 0xfc9Cf30409b8FF54Ea93addc678bDCa1f68a93c1
AWP ++ token pool: 0x845fE0DDEf3AbBc774a0C7C7435691c40C4da8b6
AWP ++ Uniswap pool: 0x0a9d335c5cfd0601f1ab1f7ae8dcf165840f08fa
